#!/usr/bin/env python3

import os
import argparse

def createParser():
    p = argparse.ArgumentParser(
        prog = 'Day Maker/Copier',
        description= 'Creates all the needed files to start coding a new day for AOC.',
        epilog= 'If there are any errors, they will probably never get fixed. '
    )
    p.add_argument('-i', required=True, dest='day_input'  , help='The number of the day to create all the files from.')
    return p.parse_args()

def createDayFiles(p):
    dayNum = p.day_input
    newDayDir = "/home/frankie/aoc2022/day" + dayNum + "/"
    os.system("mkdir " + newDayDir)
    os.system("touch " + newDayDir + "day" + dayNum + ".cpp")
    os.system("touch " + newDayDir + "day" + dayNum + ".py")
    os.system("touch " + newDayDir + "small_input_day" + dayNum + ".txt")
    os.system("touch " + newDayDir + "large_input_day" + dayNum + ".txt")
    os.system("touch " + newDayDir + "day" + dayNum + ".out")

def main():
    p = createParser()
    createDayFiles(p)

if __name__ == "__main__":
    main()